[package]
name = "ress-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# ress
ress-primitives.workspace = true
ress-network.workspace = true
ress-protocol.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true

# reth
reth-primitives.workspace = true
reth-chainspec.workspace = true
reth-storage-errors.workspace = true
reth-revm.workspace = true

# misc
thiserror.workspace = true
rusqlite.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3.3"
tracing-subscriber.workspace = true
