[package]
name = "ress"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# ress
ress-provider.workspace = true
ress-network.workspace = true
ress-engine.workspace = true
ress-testing.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-network.workspace = true
alloy-serde.workspace = true

# reth
reth-ress-protocol.workspace = true
reth-ethereum-primitives.workspace = true
reth-chainspec.workspace = true
reth-network.workspace = true
reth-network-peers.workspace = true
reth-discv4.workspace = true
reth-db-api.workspace = true
reth-storage-api.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-node-events.workspace = true
reth-node-metrics.workspace = true
reth-engine-tree.workspace = true
reth-rpc-eth-types.workspace = true
reth-rpc-engine-api.workspace = true
reth-rpc-api.workspace = true
reth-rpc-builder.workspace = true
reth-rpc.workspace = true
reth-consensus-debug-client.workspace = true
reth-payload-builder.workspace = true
reth-transaction-pool.workspace = true
reth-cli.workspace = true
reth-cli-util.workspace = true
reth-ethereum-cli.workspace = true
reth-tasks.workspace = true

# misc
clap.workspace = true
eyre.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
metrics.workspace = true
dirs-next = "2.0"
shellexpand = "3.0"
http = "1.0"
tower = "0.4"
jsonrpsee = "0.24"
jsonrpsee-server = "0.24"
async-trait = "0.1.68"

[build-dependencies]
vergen = { version = "9.0", features = ["build"] }
vergen-git2 = "1.0"
